[package]
name = "qsonaut-third-party"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "QSONaut adapters around third-party modem implementations"
repository = "https://github.com/nicksbar/qsonaut-third-party"

[dependencies]
qsonaut-modems.workspace = true
mfsk-core.workspace = true
thiserror.workspace = true
image.workspace = true
komitoto-sstv.workspace = true
cwdit-dsp.workspace = true
cwdit-morse.workspace = true
